"""Today's observed behaviour at e7020879, one row per query answer, change and refusal.

Generated once from report.run_all and reviewed row by row against the specimen
files; test_g3.py asserts every row. A row that changes means Core's behaviour
or the harness changed, and the change needs reading, not regenerating.

QUERIES: (specimen, query, branch) -> (classification, fields Core answered wrong,
    fields not expressible, reasons for the not-expressible fields)
CHANGES: (specimen, position) -> Core outcome of the declared change
REFUSALS: (specimen, refusal) -> (classification, procedure steps as
    (supersession attempted, outcome, stage, reason, detail), alternatives)
"""

QUERIES = {('g1-01', 'C01', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-01', 'C02', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'previous_refs', 'new_refs', 'new_cell_refs'),
                        ('the new premise must be selected by domain time and account',)),
 ('g1-01', 'C05', ''): ('NOT_EXPRESSIBLE', (), ('state',), ('Core has no premise-compatibility or common-applicability operation',)),
 ('g1-01', 'P01', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'P02', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'value', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'P03', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'value', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'P04', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'value', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'P05', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'value', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'P06', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'value', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'P07', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'value', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'P08', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'P09', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'value', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'P10', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'value', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-01', 'PC-NOT-COMPUTED', ''): ('NOT_EXPRESSIBLE', (), ('state',), ('the premise must first be selected by domain time and account',)),
 ('g1-01', 'PH-K0', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-01', 'PH-K1', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-01', 'PH-K2', ''): ('ANSWERED_WRONG',
                          ('metadata[a2].knowledge_until',),
                          ('visible_refs', 'metadata[a1].knowledge_until'),
                          ('records and current versions match; older versions a1 are reachable only by replay_at at their own position, '
                           'and no read lists them',
                           'older version: not in this read')),
 ('g1-01', 'PH-K3', ''): ('NOT_EXPRESSIBLE',
                          (),
                          ('visible_refs',),
                          ('records and current versions match; older versions a1 are reachable only by replay_at at their own position, '
                           'and no read lists them',)),
 ('g1-01', 'PH-K3-META', ''): ('ANSWERED_WRONG',
                               ('metadata[a2].knowledge_until',),
                               ('visible_refs', 'metadata[a1].knowledge_until'),
                               ('records and current versions match; older versions a1 are reachable only by replay_at at their own '
                                'position, and no read lists them',
                                'older version: not in this read')),
 ('g1-01', 'PX-r1-K3', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ01', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ02', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ03', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ04', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ05', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ06', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ07', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ08', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'selected_refs', 'unresolved_refs'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-02', 'OQ09', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ10', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ11', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ12', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ13', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-02', 'OQ14', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-03', 'CA01', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'selected_refs', 'value'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-03', 'CA02', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'selected_refs', 'value'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-03', 'CA03', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'candidate_refs'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-03', 'CA04', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'selected_refs', 'value', 'basis'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-03', 'CA05', 'Assumptions enter only when their account is named'): ('NOT_EXPRESSIBLE',
                                                                           (),
                                                                           ('state', 'candidate_refs'),
                                                                           ('no Core read takes a domain time, account precedence, '
                                                                            'named-use context or persistence rule',)),
 ('g1-03', 'CA05', 'Every accepted account is a candidate'): ('NOT_EXPRESSIBLE',
                                                              (),
                                                              ('state', 'candidate_refs'),
                                                              ('no Core read takes a domain time, account precedence, named-use context or '
                                                               'persistence rule',)),
 ('g1-03', 'CA06', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-03', 'CA07', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'selected_refs', 'value'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-03', 'CA08', 'A use selection binds only that use'): ('NOT_EXPRESSIBLE',
                                                            (),
                                                            ('state', 'candidate_refs'),
                                                            ('no Core read takes a domain time, account precedence, named-use context or '
                                                             'persistence rule',)),
 ('g1-03', 'CA08', 'An adopter-declared default authority resolves unscoped requests'): ('NOT_EXPRESSIBLE',
                                                                                         (),
                                                                                         ('state', 'selected_refs', 'value'),
                                                                                         ('no Core read takes a domain time, account '
                                                                                          'precedence, named-use context or persistence '
                                                                                          'rule',)),
 ('g1-03', 'CA09', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-03', 'CA10', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'selected_refs', 'value'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-04', 'C06', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'unresolved_refs'),
                        ('Core has no premise-compatibility or common-applicability operation',)),
 ('g1-04', 'S01', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-04', 'S02', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-04', 'S03', ''): ('NOT_EXPRESSIBLE',
                        (),
                        ('state', 'selected_refs', 'unresolved_refs'),
                        ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-04', 'S04', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-04', 'SQ-ACCOUNT-M1', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-04', 'SQ-ACCOUNT-M2', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-04', 'SQ-EXACT-m1', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-05', 'CC01', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-05', 'CC02', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-05', 'CC03', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-05', 'CC04', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-05', 'CC05', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'conflict_refs'),
                         ('Core has no premise-compatibility or common-applicability operation',)),
 ('g1-05', 'CC06', ''): ('NOT_EXPRESSIBLE', (), ('state',), ('Core has no premise-compatibility or common-applicability operation',)),
 ('g1-05', 'CC07', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'conflict_refs'),
                         ('Core has no premise-compatibility or common-applicability operation',)),
 ('g1-06', 'AJ01', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-06', 'AJ02', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-06', 'AJ03', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-06', 'AJ04', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-06', 'AJ05', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-06', 'AJ06', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('metadata[D1].reconsideration', 'metadata[D2].reconsideration'),
                         ('Core has no reconsideration flag',)),
 ('g1-06', 'AJ07', 'Derived from declared premises'): ('NOT_EXPRESSIBLE',
                                                       (),
                                                       ('metadata[D1].reconsideration', 'metadata[D2].reconsideration'),
                                                       ('Core has no reconsideration flag',)),
 ('g1-06', 'AJ07', 'Recorded by a reviewer; none recorded yet'): ('NOT_EXPRESSIBLE',
                                                                  (),
                                                                  ('metadata[D1].reconsideration', 'metadata[D2].reconsideration'),
                                                                  ('Core has no reconsideration flag',)),
 ('g1-06', 'AJ08', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-06', 'AJ09', 'Declared rule: any argument with no revised premise suffices'): ('NOT_EXPRESSIBLE',
                                                                                     (),
                                                                                     ('metadata[C1].support_sufficiency',
                                                                                      'metadata[C1].supporting_refs'),
                                                                                     ('Core has no support or sufficiency field',)),
 ('g1-06', 'AJ09', 'No declared sufficiency rule'): ('NOT_EXPRESSIBLE',
                                                     (),
                                                     ('metadata[C1].support_sufficiency',),
                                                     ('Core has no support or sufficiency field',)),
 ('g1-07', 'VQ01', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state',),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-07', 'VQ02', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-07', 'VQ03', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'unresolved_refs'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-07', 'VQ04', 'By default within its scope'): ('NOT_EXPRESSIBLE',
                                                    (),
                                                    ('state', 'derived_from_refs', 'value'),
                                                    ('no Core read takes a domain time, account precedence, named-use context or '
                                                     'persistence rule',)),
 ('g1-07', 'VQ04', 'Only when named by the caller'): ('NOT_EXPRESSIBLE',
                                                      (),
                                                      ('state', 'unresolved_refs'),
                                                      ('no Core read takes a domain time, account precedence, named-use context or '
                                                       'persistence rule',)),
 ('g1-07', 'VQ05', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'derived_from_refs', 'value'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-07', 'VQ06', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'derived_from_refs', 'value'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-07', 'VQ07', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'derived_from_refs', 'value'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-07', 'VQ08', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'derived_from_refs', 'value'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-07', 'VQ09', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state',),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-07', 'VQ10', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'derived_from_refs', 'value'),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-07', 'VQ11', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state',),
                         ('no Core read takes a domain time, account precedence, named-use context or persistence rule',)),
 ('g1-07', 'VQ12', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-07', 'VQ13', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-08', 'ST01', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-08', 'ST02', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-08', 'ST03', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-08', 'ST04', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-08', 'ST05', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-08', 'ST06', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-08', 'ST07', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-08', 'ST08', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'missing_refs'),
                         ('no public API rebuilds a history with a retained artifact withheld',)),
 ('g1-08', 'ST09', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'missing_refs'),
                         ('no public API rebuilds a history with a retained artifact withheld',)),
 ('g1-08', 'ST10', ''): ('NOT_EXPRESSIBLE',
                         (),
                         ('state', 'missing_refs'),
                         ('no public API rebuilds a history with a retained artifact withheld',)),
 ('g1-08', 'ST11', 'Any missing retained artifact refuses the whole rebuild'): ('NOT_EXPRESSIBLE',
                                                                                (),
                                                                                ('state', 'missing_refs'),
                                                                                ('no public API rebuilds a history with a retained '
                                                                                 'artifact withheld',)),
 ('g1-08', 'ST11', 'Only reads whose closure needs it refuse'): ('NOT_EXPRESSIBLE',
                                                                 (),
                                                                 ('state', 'premise_refs', 'model_ref', 'result_ref', 'value'),
                                                                 ('no public API rebuilds a history with a retained artifact withheld',)),
 ('g1-08', 'ST12', ''): ('ANSWERED_CORRECT', (), (), ()),
 ('g1-08', 'ST13', ''): ('ANSWERED_CORRECT', (), (), ())}

CHANGES = {('g1-01', 'K0'): 'GENESIS',
 ('g1-01', 'K1'): 'ADMITTED',
 ('g1-01', 'K1a'): 'ADMITTED',
 ('g1-01', 'K1b'): 'ADMITTED',
 ('g1-01', 'K2'): 'ADMITTED',
 ('g1-01', 'K3'): 'ADMITTED_WITHOUT_SUPERSESSION',
 ('g1-02', 'O0'): 'GENESIS',
 ('g1-02', 'O1'): 'ADMITTED',
 ('g1-02', 'O10'): 'ADMITTED',
 ('g1-02', 'O2'): 'ADMITTED',
 ('g1-02', 'O3'): 'ADMITTED',
 ('g1-02', 'O4'): 'ADMITTED',
 ('g1-02', 'O5'): 'ADMITTED',
 ('g1-02', 'O6'): 'ADMITTED',
 ('g1-02', 'O7'): 'ADMITTED',
 ('g1-02', 'O8'): 'ADMITTED',
 ('g1-02', 'O9'): 'ADMITTED',
 ('g1-03', 'A0'): 'GENESIS',
 ('g1-03', 'A1'): 'ADMITTED',
 ('g1-03', 'A2'): 'ADMITTED',
 ('g1-03', 'A3'): 'ADMITTED',
 ('g1-03', 'A4'): 'ADMITTED',
 ('g1-04', 'M0'): 'GENESIS',
 ('g1-04', 'M1'): 'ADMITTED',
 ('g1-04', 'M2'): 'ADMITTED',
 ('g1-05', 'G0'): 'GENESIS',
 ('g1-05', 'G1'): 'ADMITTED',
 ('g1-05', 'G2'): 'ADMITTED',
 ('g1-05', 'G3'): 'ADMITTED',
 ('g1-06', 'J0'): 'GENESIS',
 ('g1-06', 'J1p'): 'ADMITTED',
 ('g1-06', 'J2p'): 'ADMITTED',
 ('g1-06', 'J3p'): 'ADMITTED',
 ('g1-06', 'J4p'): 'ADMITTED',
 ('g1-07', 'V0'): 'GENESIS',
 ('g1-07', 'V1'): 'ADMITTED',
 ('g1-07', 'V2'): 'ADMITTED',
 ('g1-07', 'V3'): 'ADMITTED',
 ('g1-07', 'V4'): 'ADMITTED',
 ('g1-08', 'R0'): 'GENESIS',
 ('g1-08', 'R1'): 'COLLAPSED_INTO_GENESIS',
 ('g1-08', 'R2'): 'SPLIT',
 ('g1-08', 'R3'): 'ADMITTED',
 ('g1-08', 'R4'): 'ADMITTED'}

REFUSALS = {('g1-01', 'RF-OVERLAP'): ('EXPECTED_REFUSAL_NOT_OBSERVED',
                           ((True,
                             'REFUSED',
                             'CHECK',
                             'CONTENT_RULE_VIOLATED',
                             'VIOLATED: STRUCTURAL_REFUSAL: record supersession forks prior record: r1'),
                            (False, 'ADMITTED', None, None, None)),
                           {}),
 ('g1-01', 'RF-STALE-BASE'): ('EXPECTED_REFUSAL_OBSERVED',
                              ((True,
                                'REFUSED',
                                'CHECK',
                                'CONTENT_RULE_VIOLATED',
                                'VIOLATED: STRUCTURAL_REFUSAL: record supersession forks prior record: r1'),
                               (False, 'REFUSED', 'ADMIT', 'STALE_BASE', 'change-set base ledger head is stale')),
                              {}),
 ('g1-02', 'RF-BORROWED'): ('EXPECTED_REFUSAL_NOT_OBSERVED', ((False, 'ADMITTED', None, None, None),), {}),
 ('g1-02', 'RF-STALE-EXEC'): ('EXPECTED_REFUSAL_OBSERVED',
                              ((False, 'REFUSED', 'ADMIT', 'STALE_BASE', 'change-set base ledger head is stale'),),
                              {}),
 ('g1-05', 'RF-CITED-MODEL'): ('EXPECTED_REFUSAL_OBSERVED',
                               ((False,
                                 'REFUSED',
                                 'CHECK',
                                 'CONTENT_RULE_VIOLATED',
                                 "VIOLATED: STRUCTURAL_REFUSAL: Target 'work:SM' has type 'Subject', expected "
                                 "'https://example.malleus.dev/temporal-g3/g1-05/Model' for UsesModel"),),
                               {'model link as a slot only': (('ADMITTED', None, None),)}),
 ('g1-06', 'RF-STALE-REVIEW'): ('EXPECTED_REFUSAL_OBSERVED',
                                ((True,
                                  'REFUSED',
                                  'CHECK',
                                  'CONTENT_RULE_VIOLATED',
                                  'VIOLATED: STRUCTURAL_REFUSAL: record supersession forks prior record: J1'),
                                 (False, 'REFUSED', 'ADMIT', 'STALE_BASE', 'change-set base ledger head is stale')),
                                {'composed fresh at J4p (base not stale)': (('REFUSED', 'CHECK', 'CONTENT_RULE_VIOLATED'),
                                                                            ('ADMITTED', None, None))}),
 ('g1-07', 'RF-NO-EVIDENCE'): ('EXPECTED_REFUSAL_OBSERVED',
                               ((False,
                                 'REFUSED',
                                 'CHECK',
                                 'CONTENT_RULE_VIOLATED',
                                 "VIOLATED: STRUCTURAL_REFUSAL: Class 'https://example.malleus.dev/temporal-g3/g1-07/ReportedEvent' must "
                                 "satisfy exactly one declared alternative; matched 0; Required slot 'evidence_refs' missing"),),
                               {'change set names no source at all': (('REFUSED', 'COMPOSE', 'MALFORMED_CHANGE_SET'),)}),
 ('g1-08', 'RF-MISSING-CONTRACT'): ('EXPECTED_REFUSAL_OBSERVED',
                                    ((False, 'REFUSED', 'ADMIT', 'STALE_BASE', 'change set names a different effective contract'),),
                                    {"contract named only in the record's contract_ref slot": (('ADMITTED', None, None),)}),
 ('g1-08', 'RF-MISSING-EVIDENCE'): ('EXPECTED_REFUSAL_OBSERVED',
                                    ((True,
                                      'REFUSED',
                                      'CHECK',
                                      'CONTENT_RULE_VIOLATED',
                                      'VIOLATED: STRUCTURAL_REFUSAL: record replacement contradicts prior valid time: q-price'),
                                     (False,
                                      'REFUSED',
                                      'CHECK',
                                      'CONTENT_RULE_VIOLATED',
                                      "VIOLATED: STRUCTURAL_REFUSAL: Class 'https://example.malleus.dev/temporal-g3/g1-08/Assertion' must "
                                      "satisfy exactly one declared alternative; matched 0; Required slot 'evidence_refs' missing")),
                                    {}),
 ('g1-08', 'RF-MISSING-MODEL'): ('EXPECTED_REFUSAL_OBSERVED',
                                 ((False,
                                   'REFUSED',
                                   'CHECK',
                                   'CONTENT_RULE_VIOLATED',
                                   "VIOLATED: STRUCTURAL_REFUSAL: Target entity 'phantom:model' does not exist"),),
                                 {'model link as a slot only': (('ADMITTED', None, None),)}),
 ('g1-08', 'RF-PARTIAL'): ('EXPECTED_REFUSAL_OBSERVED',
                           ((False,
                             'REFUSED',
                             'CHECK',
                             'CONTENT_RULE_VIOLATED',
                             "VIOLATED: STRUCTURAL_REFUSAL: Target entity 'phantom:subject' does not exist"),),
                           {}),
 ('g1-08', 'RF-UNSUPPORTED'): ('EXPECTED_REFUSAL_OBSERVED',
                               ((False, 'REFUSED', 'COMPOSE', 'MALFORMED_CHANGE_SET', 'unsupported valid-time kind: RECURRING'),),
                               {})}
